### PR TITLE
[Hacktoberfest] Project & Issues  added 

### PR DESCRIPTION
**Pull request by aminoxix**
**Description:-**
A Project (hello-world :wave:) and some issues of hello-world :wave: & `DEVSTRONS' Contest Bot` are added.

**Note for reviewers:-**
Ready to review! :eyes: 

Thanks! :slightly_smiling_face:

### CODE REVIEW

**Comment by thisisamank** [comment]
Please resolve merge conflicts

**Comment by amino19** [comment]
@thisisamank: Pl take it now! :heavy_check_mark:

**Comment by thisisamank** [comment]
There are a lot of changes, please make a new PR.

**Comment by amino19** [comment]
@vinitshahdeo: Pl check this issue, it already flexes in my profile & also, I participated as a mentor here.
It's not a good way to close any pull request without having logical info., if the reviewer has a lack of knowledge about how to review pull requests there's a way towards Open source dishonor!

I'd work in a lot of reputed Open source organizations, so far I didn't see such as @thisisamank. 
Hope you understand this issue, pl open this again, I'll gonna commit here with one commit by squashing it.

**Pull request merged**
