### PR TITLE
Update MENTORS.md

### PR DESCRIPTION
**Pull request by Abhinav-26**

### CODE REVIEW

**Comment by iamdevvalecha** [comment]
@Abhinav-26 resolve conflicts.

**Comment by iamdevvalecha** [comment]
@Abhinav-26 hey, if you have any projects please send the pr or dm me i will add it.

**Comment by Abhinav-26** [comment]
Yeah, sure. Will let you know you or raise a PR for those.

**Comment by iamdevvalecha** [comment]
@Abhinav-26 thanks

**Pull request merged**
