### PR TITLE
Update ADD_NEW_MENTOR.md

### PR DESCRIPTION
**Pull request by vijetasaini0211**

### CODE REVIEW

**Review by vinitshahdeo — COMMENTED** [review]
@vijetasaini0211 can you please add these details to `MENTORS.md`?

**Comment by vijetasaini0211** [comment]
> @vijetasaini0211 can you please add these details to `MENTORS.md`?

Yeah! I've made a PR to MENTORS.md.

**Comment by thisisamank** [comment]
Hi @vijetasaini0211 I can't see the changes in `mentors.md` file. Can you please have a look?

**Comment by vijetasaini0211** [comment]
> Hi @vijetasaini0211 I can't see the changes in `mentors.md` file. Can you please have a look?

Yeah! I 've added my details and PR is merged. You can see the details at 31 in the list.

**Comment by thisisamank** [comment]
> > Hi @vijetasaini0211 I can't see the changes in `mentors.md` file. Can you please have a look?
> 
> Yeah! I 've added my details and PR is merged. You can see the details at 31 in the list.

Cool, Thanks for being a mentor :)

**Pull request closed without merging**
