### PR TITLE
added my project to PROJECTS.md

### PR DESCRIPTION
**Pull request by ankushKun**
Added [opensea api](https://github.com/ankushKun/opensea) to `PROJECTS.md`

### CODE REVIEW

**Comment by thisisamank** [comment]
Hi @ankushKun The formatting of `PROJECTS.md` is disturbed, can you please resolve this?

**Comment by ankushKun** [comment]
@thisisamank I'm really sorry for messing up the formatting, VSCode auto formatted it and I did not notice 😆 
I copied the latest contents from `PROJECTS.md` and have fixed it, it should be fine now :)
Thanks

**Comment by vinitshahdeo** [comment]
@ankushKun Please resolve the conflicts.

**Comment by ankushKun** [comment]
@vinitshahdeo resolved!

**Comment by thisisamank** [comment]
@ankushKun Thanks for adding the projects :)

**Pull request merged**
