### PR TITLE
Added a new project "LeafLet"

### PR DESCRIPTION
**Pull request by Jassi10000**
Added a new project in Projects.md called "LeafLet"

### CODE REVIEW

**Comment by iamdevvalecha** [comment]
@Jassi10000 please resolve conflicts. thank you.

**Review by iamdevvalecha — APPROVED** [review]

**Comment by Jassi10000** [comment]
I have merged the conflicts , idk why they are not getting reflected

**Comment by iamdevvalecha** [comment]
@Jassi10000 i have resolved it.

**Comment by Jassi10000** [comment]
@iamdevvalecha Is there any limit to how many projects one mentor has to contribute ? 
Coz am researching them , so I hope multiple PRs are acceptable ?

**Pull request merged**
