### PR TITLE
added link to become a mentor

### PR DESCRIPTION
**Pull request by ishikaamittal**
Ishika Mittal | https://github.com/ishikaamittal | https://www.linkedin.com/in/ishika-mittal-2a3242183/ | Python Developer

### CODE REVIEW

**Review by vinitshahdeo — COMMENTED** [review]
@ishikaamittal Please add these details to `MENTORS.md`

**Comment by ishikaamittal** [comment]
> @ishikaamittal Please add these details to `MENTORS.md`

added

**Comment by vinitshahdeo** [comment]
@ishikaamittal I don't see it in `diff`.  Can you please check once?

**Comment by ishikaamittal** [comment]
> @ishikaamittal I don't see it in `diff`. Can you please che

**Comment by ishikaamittal** [comment]
> @ishikaamittal I don't see it in `diff`. Can you please check once?

**Comment by thisisamank** [comment]
Hi @ishikaamittal you have been added into `mentors.md` file so I am closing this PR now.

**Pull request closed without merging**
