### PR TITLE
Request to become mentor

### PR DESCRIPTION
**Pull request by wimpywarlord**
Added my name in the mentors.md

### CODE REVIEW

**Review by vinitshahdeo — APPROVED** [review]

**Comment by wimpywarlord** [comment]
could you elaborate on what you mean by "can you take the latest pull"?

**Comment by iamdevvalecha** [comment]
@wimpywarlord hey, if you have any projects please send the pr or dm me i will add it.

**Comment by wimpywarlord** [comment]
@iamdevvalecha sure, I would love that.

I am not sure how can I dm you on GitHub? (I would love to connect with you on other social media platforms) 

Additionally, I didn't understand how to put a PR for project suggestions, Instead, I created an Issue and tagged you in it.

**Comment by iamdevvalecha** [comment]
> @iamdevvalecha sure, I would love that.
> 
> I am not sure how can I dm you on GitHub? (I would love to connect with you on other social media platforms)
> 
> Additionally, I didn't understand how to put a PR for project suggestions, Instead, I created an Issue and tagged you in it.

https://www.linkedin.com/in/iamdevvalecha/ we can connect over linkedin.

**Pull request merged**
