### PR TITLE
Add my name to mentors list

### PR DESCRIPTION
**Pull request by arsheelsheikh**

### CODE REVIEW

**Review by vinitshahdeo — CHANGES_REQUESTED** [review]
@arsheelsheikh can you please take the latest pull and resolve the conflicts?

**Comment by arsheelsheikh** [comment]
should I close this PR and create a new one

**Comment by arsheelsheikh** [comment]
I have resolved the conflict

**Comment by arsheelsheikh** [comment]
I have resolved the conflict do review it once

**Pull request merged**
