### PR TITLE
Updated my details in Mentor.md

### PR DESCRIPTION
**Pull request by drishtipeshwani**
I have updated my details in Mentor.md

### CODE REVIEW

**Comment by vanshika-srivastava** [comment]
Hey @drishtipeshwani you  have added your details in template

**Comment by vanshika-srivastava** [comment]
Please fork the repo and raise a PR in Mentors.md . You can check out Mentors.md to understand the format . This is just a template .

**Comment by drishtipeshwani** [comment]
Ya, sure , I thought we had to make fork and make changes in template and raise a pull request. I will raise another pull request.

**Comment by vanshika-srivastava** [comment]
Yes please , thank you

**Pull request closed without merging**
