### PR TITLE
Added flutter app repository

### PR DESCRIPTION
**Pull request by viveeeeeek**
Added Flutter Body Mass Index calculator app repository.

### CODE REVIEW

**Review by Jassi10000 — CHANGES_REQUESTED** [review]
Please make 142. Project go in the next line

You can see how other projects have been structured , pls maintain the structure
Make asked changes

**Review by Jassi10000 — COMMENTED** [review]
That's perfect !!!!!! 
Someone will be reviewing and then will merge it

Thanks for contributing!!
All the best !!

**Comment by viveeeeeek** [comment]
Hey @Jassi10000 Thankyou. is there something wrong? Because in Hacktoberfest dashboard it is showing me that "Exluded Project"

**Comment by Jassi10000** [comment]
> Hey @Jassi10000 Thankyou. is there something wrong? Because in Hacktoberfest dashboard it is showing me that "Exluded Project"

Can you post a screenshot of your issue here , so that I can better understand ur issue

**Comment by viveeeeeek** [comment]
Sure. 
image

**Comment by Jassi10000** [comment]
@viveeeeeek See if you are mentoring , then all the PRs to this repo will not be counted 
coz this is a repo for resouces by mentors and not a code repo

**Comment by viveeeeeek** [comment]
Oh. Thanks, @Jassi10000. I didn't know about that. This is my first time managing a repository. Sorry If bothered you.

**Comment by Jassi10000** [comment]
> Oh. Thanks, @Jassi10000. I didn't know about that. This is my first time managing a repository. Sorry If bothered you.

Nevermind
we mentors are here to help you only

**Pull request merged**
