### PR TITLE
open source software

### PR DESCRIPTION
**Pull request by njnv-001**
open source software

### CODE REVIEW

**Review by Jassi10000 — COMMENTED** [review]
@njnv-001 Buddy can you pls tell what does this contribution of yours does 
Can you pls brief it so that if found relevant , we can move ahead with reviewing and merging

**Comment by njnv-001** [comment]
i add some popular open source software  name that is free to use .please merge it.

**Comment by Jassi10000** [comment]
Okayy !!!
But how does it helps in improving the repository 
See if you new to Open Source and are worried about making contributions , just head over to explore folder and you can see ISSUES.md and PROJECTS.md . There you will find a list of good beginner level issues and projects that involve basic contributions . If you have any queries or issues , just feel free to ping me on my socials anytime 
I will definitely help you

**Comment by njnv-001** [comment]
y sir i am beginner in open source.ok sir

**Comment by thisisamank** [comment]
@njnv-001 Please don't spam by creating an irrelevant PR, chances are your PR will not be merged and you can be reported by the maintainer as spam and you will not be eligible for Hacktoberfest challenge after then. Kindly refrain from doing such things. This also creates a bad impression of you in the community.

**Pull request closed without merging**
