### PR TITLE
updated mentors.md

### PR DESCRIPTION
**Pull request by Vishnurr2k01**

### CODE REVIEW

**Comment by deephunt3r** [comment]
@Vishnurr2k01 Thanks for your interest! There are some merge conflicts in your branch, Could you please resolve them 😄

**Comment by Vishnurr2k01** [comment]
yah sure i will fix that

**Comment by thisisamank** [comment]
Hi, can you please make a new PR with your details?

**Comment by Vishnurr2k01** [comment]
> Hi, can you please make a new PR with your details?

Mentors.Md right? What sl no should i put.

**Pull request closed without merging**
