### PR TITLE
added link to become a mentor

### PR DESCRIPTION
**Pull request by Ismriti12**
Basic information
Name: Ismriti Gupta
LinkedIn: https://www.linkedin.com/in/ismriti/
Twitter: https://twitter.com/ismriti_spn
About: UI/UX Designer | Machine Learning | Documentation.

Why do I want to become a mentor?
- I want to know how this open-source community works and learn from fellowmates.
- Being from a non-tech background, I understand what a person goes through while starting. Getting the right help at that time is no less than a blessing. As it helps the person to complete the project positively. 
- Want to mentor for jobtweets and Twitter Sentiment Analysis repository.

### CODE REVIEW

**Comment by thisisamank** [comment]
Hi @Ismriti12 can you please add your details in `mentors.md` file?

**Comment by Ismriti12** [comment]
added

**Comment by thisisamank** [comment]
Hi, I can't see the changes. Did you commit your changes and pushed it? Also remove extra lines that you added from `readme.md` file.

**Review by vinitshahdeo — CHANGES_REQUESTED** [review]
@Ismriti12 Please add the details to `MENTORS.md`

**Pull request closed without merging**
